name: Release Package

on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/ci.yml

  release_packages:
    needs: tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment:
        name: production

    steps:
      - name: Notify Packagist
        env:
          PACKAGIST_USER: ${{ secrets.PACKAGIST_USER }}
          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
        run: curl -XPOST -H'Content-Type:application/json' "https://packagist.org/api/update-package?username=$PACKAGIST_USER&apiToken=$PACKAGIST_TOKEN" -d "{\"repository\":\"https://github.com/open-mapsight/tile-proxy\"}"
